Repository MLH-Fellowship/0.4.1-Quarantime, pull requests merged in 2020-06, with the labels that each got.

#17 Implemented Backend Server
  .gitignore
  .idea/workspace.xml
  Passport Authentication.iml
  app.js
  config/auth.js
  config/keys.js
  config/passport.js
  graphql/resolvers/comments.js
  graphql/resolvers/index.js
  graphql/resolvers/posts.js
  graphql/resolvers/users.js
  graphql/typedefs.js
  index.js
  models/Post.js
  models/User.js
  package-lock.json
  package.json
  routes/index.js
  routes/users.js
  schema/introspectionSchema.json
  schema/schema.graphql
  util/check-auth.js
  util/validators.js
  views/dashboard.ejs
  views/layout.ejs
  views/login.ejs
  views/partials/messages.ejs
  views/register.ejs
  views/welcome.ejs
  yarn.lock
Labels: enhancement

#19 Create LICENSE
  LICENSE
Labels: discussion, documentation

#27 Update README.md
  README.md
Labels: discussion, documentation, good first issue, priority-2

#29 WIP Enhanced UI
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/LikeButton.js
  client/src/components/MenuBar.js
  client/src/components/PostCard.js
  client/src/components/PostForm.js
  client/src/fonts.css
  client/src/pages/Home.js
  client/src/pages/SinglePost.js
Labels: Do Not Merge, UI, enhancement, good first issue, help wanted, priority-3

#32 Enhanced UI
  client/src/App.css
  client/src/pages/Home.js
Labels: enhancement, priority-2
